language: go
go:
- 1.9.1
env:
  global:
  - REPO=fabzo/gcloud-directory-service
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - secure: NGuOjJQPFnR5/JAJHoh5v9+g3y+0vF2KGtRND6FtyeHX/ib4Axfi24JK2fjPvHToB+Xuy+4LALlaRHsWiomjfkfC6TFA5ccsK0xKsfK38sVn7sLs/HmVR9hmB/yleA12cA4GeKwl4UaVAZVmrCcLPRdhgAeykJsPuDKoAEvZZl9O3TCOi02AvwZoLL3b6W5h4Q7TyUtzZrknMzdc/Dfl9z58aCqABOPNQbR9MB5Ln9DA0TltWMuIX6TZgQq3pAPOXD/TjeYsG8GUH8uEM3+J48Xax8Jq8Evl+nAXv2OcaAerYVn2BKuc6p/uNpRtAbk/rcC3L06oNwCFLnMdaavOBEjPaB9tp0h6GPA6XLTjHQbywkwoUuMtmod1d3itV4ARYGB/tOpcdfMKp31Q3TyaUq33TFPnnf8HwprllHMBu5z2/yxXHLu75HRwX218lGKmJPzBgMe7gkIraslqFOsNocAxnCTBlUHF6wiIfthOce25KCTaUH72TJp0W4seh8v2DYjy5SDZ6x7aIzMLqEEVVVKSqZj5kM+7bzM93+0ark7dj07gmRhgXakBJNhafxO3jfeoRB9Pq6LIW9mO6VFNVqCZ51eYwyVNapRF2TmX5sVgsRGM+/uhSydLt87rop3feOpbu/fNxJ8cRfNgnI9zx0jomFL0uPPJGI4T1vUVMsY=
  - secure: UNNCS9OlIzsDwKNwU8liu2sbZv2hCx97Z7qQgr9TuTkC/yx4DUjZjCs75OlDHuAgqMczDc2QeojJo4MwScvV6srnprCJjvtf/IjVIhi4An5OhcDrRzlhtdYNjJJdtEkCVsVmdhzb9GMcv0fqhUNxDq8JOnAnwyQGVUgAQ9Rvul5XObtXnf6cIF2yMnsKcy3Hs7cCES9sbZwAuVlwolvVORz7GnsJOq+8be5rjNRpjM5yiPu6gRDCiBPespvRnNJQPukc+j0QEOm4U+GTzbnBbzQOrEeYvOpsikVOJKt6RkBo0Jv5JFkh5HxoY4/ywXB6mFVhsbMF+Wi9PscJxsCXGvmmaTUBFAU2u59oA1SV6uIHkemNN9BZd0OGkMwNdC5GOVwz7rWrmXw6mV5P2RioxBsSLAEwY5uIHIIsXed17xiHrKONGGep6233pgmZhfcPPq+uwt46RNm6PMBUv6u0ZmiVzyiV6xlp9THg3KL5r8BxJMq9ygJy3n2y/nnU8X/RQG1DVX+RIbO+HNH+mKzE8YD3bGDHAkX0DD+4x2GpcCFgvPu/Jrcw1r11zSdirwG+eppznB2RT9eaGZQ7yZlDMZ0b6awtVZ+l7tWGxhIOGT8z8T/O4A59npxZV1dBuYeajKWOyXjJph7EQFu60/ohOcYgj6/ORX5/xemFMyjcpGQ=
script:
- go build
- curl -o ca-certificates.crt https://curl.haxx.se/ca/cacert.pem
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo "${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}"; fi`
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
